spring.application.name=abacatepay-spring-demo

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:abacatepaydb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# AbacatePay
abacatepay.api.url=https://api.abacatepay.com/v1
abacatepay.api.key=abc_dev_kRPPW21E4ayXUTu4UMPQhDEW
abacatepay.webhook.secret=0c2bcaf0e148e1cae0849db300812b7e
abacatepay.hmac.key=t9dXRhHHo3yDEj5pVDYz0frf7q6bMKyMRmxxCPIPp3RCplBfXRxqlC6ZpiWmOqj4L63qEaeUOtrCI8P0VMUgo6iIga2ri9ogaHFs0WIIywSMg0q7RmBfybe1E5XJcfC4IW3alNqym0tXoAKkzvfEjZxV6bE0oG2zJrNNYmUCKZyV0KZ3JS8Votf9EAWWYdiDkMkpbMdPggfh1EqHlVkMiTady6jOR3hyzGEHrIz2Ret0xHKMbiqkr9HS1JhNHDX9
